//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.29 at 04:24:45 PM CEST 
//


package net.euskadi.osakidetza.libs.wsclients.common.auditoria;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://osakidetza.net/soa/auditoria}dni-login"/>
 *         &lt;element ref="{http://osakidetza.net/soa/auditoria}tis-login"/>
 *         &lt;element ref="{http://osakidetza.net/soa/auditoria}cic-login"/>
 *         &lt;element ref="{http://osakidetza.net/soa/auditoria}dni-paciente"/>
 *         &lt;element ref="{http://osakidetza.net/soa/auditoria}tis-paciente"/>
 *         &lt;element ref="{http://osakidetza.net/soa/auditoria}cic-paciente"/>
 *         &lt;element ref="{http://osakidetza.net/soa/auditoria}codigo-aplicacion"/>
 *         &lt;element ref="{http://osakidetza.net/soa/auditoria}timestamp"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dniLogin",
    "tisLogin",
    "cicLogin",
    "dniPaciente",
    "tisPaciente",
    "cicPaciente",
    "codigoAplicacion",
    "timestamp"
})
@XmlRootElement(name = "auditoria", namespace="http://osakidetza.net/soa/auditoria")
public class Auditoria {

    @XmlElement(name = "dni-login", required = true, namespace="http://osakidetza.net/soa/auditoria")
    protected String dniLogin;
    @XmlElement(name = "tis-login", required = true, namespace="http://osakidetza.net/soa/auditoria")
    protected BigInteger tisLogin;
    @XmlElement(name = "cic-login", required = true, namespace="http://osakidetza.net/soa/auditoria")
    protected BigInteger cicLogin;
    @XmlElement(name = "dni-paciente", required = true, namespace="http://osakidetza.net/soa/auditoria")
    protected String dniPaciente;
    @XmlElement(name = "tis-paciente", required = true, namespace="http://osakidetza.net/soa/auditoria")
    protected BigInteger tisPaciente;
    @XmlElement(name = "cic-paciente", required = true, namespace="http://osakidetza.net/soa/auditoria")
    protected BigInteger cicPaciente;
    @XmlElement(name = "codigo-aplicacion", required = true, namespace="http://osakidetza.net/soa/auditoria")
    protected String codigoAplicacion;
    @XmlElement(name= "timestamp", required = true, namespace="http://osakidetza.net/soa/auditoria")
    protected BigInteger timestamp;

    /**
     * Gets the value of the dniLogin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDniLogin() {
        return dniLogin;
    }

    /**
     * Sets the value of the dniLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDniLogin(String value) {
        this.dniLogin = value;
    }

    /**
     * Gets the value of the tisLogin property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTisLogin() {
        return tisLogin;
    }

    /**
     * Sets the value of the tisLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTisLogin(BigInteger value) {
        this.tisLogin = value;
    }

    /**
     * Gets the value of the cicLogin property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCicLogin() {
        return cicLogin;
    }

    /**
     * Sets the value of the cicLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCicLogin(BigInteger value) {
        this.cicLogin = value;
    }

    /**
     * Gets the value of the dniPaciente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDniPaciente() {
        return dniPaciente;
    }

    /**
     * Sets the value of the dniPaciente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDniPaciente(String value) {
        this.dniPaciente = value;
    }

    /**
     * Gets the value of the tisPaciente property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTisPaciente() {
        return tisPaciente;
    }

    /**
     * Sets the value of the tisPaciente property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTisPaciente(BigInteger value) {
        this.tisPaciente = value;
    }

    /**
     * Gets the value of the cicPaciente property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCicPaciente() {
        return cicPaciente;
    }

    /**
     * Sets the value of the cicPaciente property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCicPaciente(BigInteger value) {
        this.cicPaciente = value;
    }

    /**
     * Gets the value of the codigoAplicacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoAplicacion() {
        return codigoAplicacion;
    }

    /**
     * Sets the value of the codigoAplicacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoAplicacion(String value) {
        this.codigoAplicacion = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTimestamp(BigInteger value) {
        this.timestamp = value;
    }

}
